[package]
name = "mp_indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
# Переменные окружения (Загрузка .env).
dotenv = "0.15"

# Асинхронный рантайм
tokio = { version = "1", features = ["full"] }

# HTTP клиент для запросов к Ollama и Qdrant.
reqwest = { version = "0.11", features = ["json"] }

# Сериализация/десериализация JSON.
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Для работы с путями к файлам.
walkdir = "2"

# Для UUID (Генерация уникальных ID для чанков).
uuid = { version = "1", features = ["v4"] }

# Для логирования.
tracing = "0.1"
tracing-subscriber = "0.3"

# Для обработки ошибок.
anyhow = "1"

# Клиент для Qdrant
qdrant-client = "1.18.0"

# Цвет в консоли.
colored = "2.0"